name = "BloodStorageInSilico"
uuid = "12fa0bc3-1996-4702-b249-fafc788310f3"
version = "1.0.0"
authors = ["Alicia M. Key <alicia.m.key@cuanschutz.edu"]

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
DifferentialEquations = "7.17.0"
